version: '3.1'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my-db

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo

  cars:
    image: alm_cars
#    build: .
    ports:
      - 8085:8080
#    environment:
#      MY_DATABASE_HOST: mongo
#      MY_DATABASE_USER: root
#      MY_DATABASE_PASSWORD: password
#      MY_DATABASE_NAME: RandomDb
#      MY_DATABASE_PORT: 27017
    depends_on:
      - mongo
