version: '3.1'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my-proddb

  mongo-express:
    image: mongo-express
    ports:
    - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo

  cars:
    image: alm_cars
    ports:
      - 8085:8080
    environment:
      MY_DATABASE_HOST: mongo
      MY_DATABASE_USER: admin
      MY_DATABASE_PASSWORD: password
      MY_DATABASE_NAME: my-proddb
      MY_DATABASE_PORT: 27017
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo
