name: Greeter


on:
  workflow_dispatch:



jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: step 1, helo
        run: echo Helo Team!

      - name: step 2, bye
        run: echo byeee!

  greet-again:
    runs-on: ubuntu-20.04

    steps:
      - name: step 1, helo
        run: echo Helo Team!

      - name: step 2, bye
        run: echo byeee!